services:

  gateway:
    image: estategateway
    restart: always
    ports:
      - "8080:8080"

  discovery:
    image: estatediscovery
    ports:
      - "8761:8761"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=elasticsearch


  backend:
    image: rjgallac/searchapp:latest
    ports:
      - "8090:8090"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]

  estateinfobackenddb:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: estatesearch
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MYSQL_ROOT_HOST: "%"

  estateinfobackend:
    image: rjgallac/estateinfobackend:latest
    ports:
      - "8082:8082"
    restart: always
