spring:
  application:
    name: estategateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "http://localhost:4200,http://localhost:4300,http://estatesearch"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: estateinfobackend
          uri: lb://estateinfobackend
          predicates:
            - Path=/propertyinfo/**
        - id: estatesearch
          uri: lb://estatesearch
          predicates: Path=/search/**
        - id: analytics
          uri: lb://analyticsservice
          predicates: Path=/analyticsservice/**
        - id: imageupload
          uri: lb://imageupload
          predicates:
            - Path=/imageupload/**, /adminimageupload/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://keycloak:8888/realms/SpringbootKeycloak
            auth-server-url: http://localhost:8888/realms/SpringbootKeycloak

      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8888/realms/SpringbootKeycloak
eureka:
  client.serviceUrl.defaultZone: http://discovery:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true





